version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
#      - run:
#          command: ./manage.py test
#          name: Test
  lint:
    executor: python/default
    steps:
      - run:
        command: black --check .
        name: Lint

workflows:
  main:
    jobs:
      - build-and-test
      - lint

